# Generated by Django 5.2.1 on 2025-05-19 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_pooladvantage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='poolimage',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='PoolAdvantageDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='advantage_description', to='pools.pool')),
            ],
        ),
        migrations.DeleteModel(
            name='PoolAdvantage',
        ),
    ]
