# Generated by Django 5.2.1 on 2025-05-19 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_poolimage_description_pooladvantagedescription_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PoolAdvantageDescription',
        ),
    ]
