# Generated by Django 5.2.1 on 2025-05-19 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_remove_poolimage_description_pool_description_short_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoolDescription',
            fields=[
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='description_obj', serialize=False, to='pools.pool')),
                ('description', models.TextField(verbose_name='Полное описание')),
            ],
        ),
        migrations.RemoveField(
            model_name='pool',
            name='description',
        ),
    ]
