# Generated by Django 5.2.1 on 2025-05-21 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0006_pooldescription_remove_pool_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooldescription',
            name='description',
            field=models.TextField(),
        ),
    ]
