# Generated by Django 5.2.1 on 2025-05-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0007_alter_pooldescription_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooldescription',
            name='description',
            field=models.TextField(verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='poolimage',
            name='image',
            field=models.ImageField(upload_to='pools/'),
        ),
    ]
