# Generated by Django 5.2.1 on 2025-05-20 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_product_image_second'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_second',
        ),
    ]
