# Generated by Django 5.2.1 on 2025-05-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_remove_product_image_second'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_second',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d/'),
        ),
    ]
