# Generated by Django 5.2.1 on 2025-05-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Ваше имя*')),
                ('phone_number', models.CharField(max_length=20, verbose_name='+7 XXX XXX XX XX*')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
