# Generated by Django 5.2.1 on 2025-05-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_alter_contact_options_contact_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
        migrations.AddField(
            model_name='contact',
            name='pool_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название бассейна'),
        ),
        migrations.AddField(
            model_name='contact',
            name='pool_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, verbose_name='Слаг бассейна'),
        ),
    ]
