# Generated by Django 5.2.1 on 2025-05-21 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TermsPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description_short', models.TextField(blank=True, help_text='Короткое описание (до 300 символов)', verbose_name='Краткое описание')),
                ('main_image', models.ImageField(upload_to='terms_pools/main/')),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TermsPoolDescription',
            fields=[
                ('pool', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='description_obj', serialize=False, to='terms.termspool')),
                ('description', models.TextField(verbose_name='Полное описание')),
            ],
        ),
        migrations.CreateModel(
            name='TermsPoolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='terms_pools/gallery/')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='terms.termspool')),
            ],
        ),
    ]
