# Generated by Django 5.2.1 on 2025-07-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0004_projectcategory_projectcategoryimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projectcategory",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
