# Generated by Django 5.2.1 on 2025-05-21 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_product_image_second'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='specification',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='specification',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='order',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_second',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='popularity',
            field=models.PositiveIntegerField(choices=[(0, 'Низкая'), (1, 'Средняя'), (2, 'Высокая')], default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='reliability_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='special_notes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='product_images/'),
        ),
        migrations.RemoveField(
            model_name='specification',
            name='order',
        ),
    ]
