# Generated by Django 5.2.1 on 2025-05-21 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_category_options_alter_productimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='catalog/products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_second',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/products/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='catalog/product_images/'),
        ),
    ]
